name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Create Release
    outputs:
      release-pr: ${{ steps.release.outputs.pr }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: noirup
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: "chore(noirup): Release ${version}"

  upload-files:
    name: Upload files to release
    needs: [release-please]
    if: ${{ needs.release-please.outputs.tag-name }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./{noirup,install-windows}
          file_glob: true
          overwrite: true
          tag: ${{ needs.release-please.outputs.tag-name }}

