name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Create Release
    outputs:
      release-pr: ${{ steps.release.outputs.pr }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.NOIR_RELEASES_TOKEN }}

  upload-files:
    name: Upload files to release
    needs: [release-please]
    if: ${{ needs.release-please.outputs.tag-name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v7
        with:
          ref: ${{ needs.release-please.outputs.tag-name }}

      - name: Upload files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.NOIR_RELEASES_TOKEN }}
          file: ./{noirup,install-windows}
          file_glob: true
          overwrite: true
          tag: ${{ needs.release-please.outputs.tag-name }}
